### ISSUE TITLE
bosh creat-env (bosh-lite on VirtualBox) fails at rendering job templates

### ISSUE THREAD

**Issue by pcwizz** [cloudfoundry/bosh-deployment#179]
Following [https://bosh.io/docs/bosh-lite.html](https://bosh.io/docs/bosh-lite.html) I have executed the exert from step 4:
```
bosh create-env ~/workspace/bosh-deployment/bosh.yml \
                        --state ./state.json \
                        -o ~/workspace/bosh-deployment/virtualbox/cpi.yml \
                        -o ~/workspace/bosh-deployment/virtualbox/outbound-network.yml \
                        -o ~/workspace/bosh-deployment/bosh-lite.yml \
                        -o ~/workspace/bosh-deployment/bosh-lite-runc.yml \
                        -o ~/workspace/bosh-deployment/jumpbox-user.yml \
                        --vars-store ./creds.yml \
                        -v director_name="Bosh Lite Director" \
                        -v internal_ip=192.168.50.6 \
                        -v internal_gw=192.168.50.1 \
                        -v internal_cidr=192.168.50.0/24 \
                        -v outbound_network_name=NatNetwork
```

This commanded then emitted the following:
```
Deployment manifest: '/home/morgan/workspace/bosh-deployment/bosh.yml'
Deployment state: './state.json'

Started validating
  Downloading release 'bosh'... Finished (00:00:30)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bpm'... Finished (00:00:21)
  Validating release 'bpm'... Finished (00:00:01)
  Downloading release 'bosh-virtualbox-cpi'... Finished (00:00:28)
  Validating release 'bosh-virtualbox-cpi'... Finished (00:00:02)
  Downloading release 'bosh-warden-cpi'... Finished (00:00:20)
  Validating release 'bosh-warden-cpi'... Finished (00:00:00)
  Downloading release 'os-conf'... Finished (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'garden-runc'... Finished (00:00:32)
  Validating release 'garden-runc'... Finished (00:00:01)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:01:58)
  Validating stemcell... Finished (00:00:03)
Finished validating (00:04:29)

Started installing CPI
  Compiling package 'golang_1.7/21609f611781e8586e713cfd7ceb389cee429c5a'... Finished (00:00:18)
  Compiling package 'virtualbox_cpi/e293cbbb8359fd2cbbb9777b7b91fd142ab6c688'... Finished (00:00:14)
  Installing packages... Finished (00:00:02)
  Rendering job templates... Failed (00:00:00)
Failed installing CPI (00:00:35)

Installing CPI:
  Rendering and uploading Jobs:
    Rendering job templates for installation:
      Rendering templates for job 'virtualbox_cpi/ac9bbc51a1bb1d19719711eaaabdc94038baf2b0':
        Rendering template src: cpi.json.erb, dst: config/cpi.json:
          Rendering template src: /home/morgan/.bosh/installations/5396d6f5-a297-44f6-6113-5e78d711b609/tmp/bosh-release-job124337140/templates/cpi.json.erb, dst: /home/morgan/.bosh/installations/5396d6f5-a297-44f6-6113-5e78d711b609/tmp/rendered-jobs920059199/config/cpi.json:
            Running ruby to render templates:
              Running command: 'ruby /home/morgan/.bosh/installations/5396d6f5-a297-44f6-6113-5e78d711b609/tmp/erb-renderer768417682/erb-render.rb /home/morgan/.bosh/installations/5396d6f5-a297-44f6-6113-5e78d711b609/tmp/erb-renderer768417682/erb-context.json /home/morgan/.bosh/installations/5396d6f5-a297-44f6-6113-5e78d711b609/tmp/bosh-release-job124337140/templates/cpi.json.erb /home/morgan/.bosh/installations/5396d6f5-a297-44f6-6113-5e78d711b609/tmp/rendered-jobs920059199/config/cpi.json', stdout: '', stderr: '/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/morgan/.bosh/installations/5396d6f5-a297-44f6-6113-5e78d711b609/tmp/erb-renderer768417682/erb-render.rb:5:in `<main>'
':
                exit status 1

Exit code 1
```

**Comment by pivotal-jamil-shamy** [comment]
What is the ruby version on the machine where you are running create-env?
________________________________

**Comment by pcwizz** [comment]
`ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
`

**Comment by dpb587-pivotal** [comment]
You may want to try `gem install json` - the template rendering process relies on your local system for these ruby versions and gems. It sounds like maybe `json` was not preinstalled in your environment.
