### ISSUE TITLE
BOSH Director deployment is failing on vSphere 

### ISSUE THREAD

**Issue by prashantgnet** [cloudfoundry/bosh-deployment#379]
Running following command to deploy bosh director on vSphere environment 

`bosh create-env bosh-deployment/bosh.yml \
    --state=vars_state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/vsphere/cpi.yml \
    -o bosh-deployment/uaa.yml \
    -o bosh-deployment/vsphere/resource-pool.yml \
    -o bosh-deployment/jumpbox-user.yml \
    -o bosh-deployment/credhub.yml \
    -v director_name=test-bosh-director \
    -v internal_cidr=10.xx.xx.xx/24 \
    -v internal_gw=10.xx.xx.xx \
    -v internal_ip=10.xx.xx.xx \
    -v network_name="xxx" \
    -v vcenter_dc=xxx \
    -v vcenter_ds=xxx \
    -v vcenter_ip=10.xx.xx.xx \
    -v vcenter_user=username \
    -v vcenter_password=password \
    -v vcenter_templates=xxx \
    -v vcenter_vms=xxx \
    -v vcenter_disks=xxx \
    -v vcenter_cluster=xxx \
    -v vcenter_rp=xxx 
    `
Gives error message under uaa log file

`(36) not null primary key, created TIMESTAMP default current_timestamp, lastModified TIMESTAMP default current_timestamp, version BIGINT default 0, username VARCHAR(255) not null, password VARCHAR(255) not null, email VARCHAR(255) not null, authority BIGINT default 0, givenName VARCHAR(255) not null, familyName VARCHAR(255) not null )
org.postgresql.util.PSQLException: Connection to 10.124.71.10 closed by remote host.
Connection to 10.124.71.10 closed.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497) ~[postgresql-42.2.8.jar:42.2.8]
[passuser@v1 bosh-director-for-cf]$ eryExecutorImpl.processResults(QueryExecutorImpl.java:2233) ~[postgresql-42.2.8.jar:42.2.8]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310) ~[postgresql-42.2.8.jar:42.2.8]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446) ~[postgresql-42.2.8.jar:42.2.8]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370) ~[postgresql-42.2.8.jar:42.2.8]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311) ~[postgresql-42.2.8.jar:42.2.8]
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297) ~[postgresql-42.2.8.jar:42.2.8]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274) ~[postgresql-42.2.8.jar:42.2.8]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:269) ~[postgresql-42.2.8.jar:42.2.8]
        at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:210) ~[tomcat-jdbc-9.0.27.jar:?]
        at com.sun.proxy.$Proxy59.execute(Unknown Source) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc-9.0.27.jar:?]
        at com.sun.proxy.$Proxy59.execute(Unknown Source) ~[?:?]
        at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.`

`[2019-12-19 01:11:43.289] uaa - 16 [main] .... DEBUG --- ScriptUtils: SQLWarning ignored: SQL state '00000', error code '0', message [constraint "unique_uk_1" of relation "users" does not exist, skipping]
[2019-12-19 01:11:43.290] uaa - 16 [main] .... DEBUG --- ScriptUtils: Failed to execute SQL script statement #3 of class path resource [org/cloudfoundry/identity/uaa/db/postgresql/V1_5_2__initial_db.sql]: CREATE UNIQUE INDEX unique_uk_1_1 on users (LOWER(username))
org.postgresql.util.PSQLException: ERROR: relation "unique_uk_1_1" already exists`

and due to able error messages, credhub gives following error messages
` Could not reach the UAA server`

monit summary shows uaa is in running state but credhub is in failed state and due to this bosh director deployment is failing

**Comment by prashantgnet** [comment]
Issue resolved after adding internal DNS
