### ISSUE TITLE
Deplyment on Virtualbox failed

### ISSUE THREAD

**Issue by DigitLib** [cloudfoundry/bosh-deployment#430]
Treid to deply following Quick start and Virtualbox steps in BOSH doc, but both instrutions failed.

Ubuntu 20.04
VBox 6.1.26
Ruby 3.0.2 installed by rubenv
gem -v 3.2.22

got this err:
Failed deploying (00:02:27)

Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Building state for instance 'bosh/0':
    Rendering job templates for instance 'bosh/0':
      Rendering templates for job 'garden/05931ab9b99d8a7ce5d6fbc3fb4e577bbd55ecf985e8d7f5da08e39c17fe9017':
        Rendering template src: config/config.ini.erb, dst: config/config.ini:
          Rendering template src: /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/bosh-release-job47136666/templates/config/config.ini.erb, dst: /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/rendered-jobs1998901282/config/config.ini:
            Running ruby to render templates:
              Running command: 'ruby /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-context.json /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/bosh-release-job47136666/templates/config/config.ini.erb /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/rendered-jobs1998901282/config/config.ini', stdout: '', stderr: '/home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:189:in `rescue in render': Error filling in template '/home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/bosh-release-job47136666/templates/config/config.ini.erb' for garden/0 (line 8: #<RuntimeError: Invalid garden.listen_address '127.0.0.1': uninitialized constant TemplateEvaluationContext::IPAddr>) (RuntimeError)
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:174:in `render'
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:200:in `<main>'
/home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/bosh-release-job47136666/templates/config/config.ini.erb:8:in `rescue in parse_ip': Invalid garden.listen_address '127.0.0.1': uninitialized constant TemplateEvaluationContext::IPAddr (RuntimeError)
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/bosh-release-job47136666/templates/config/config.ini.erb:5:in `parse_ip'
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/bosh-release-job47136666/templates/config/config.ini.erb:20:in `get_binding'
	from /home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/erb.rb:905:in `eval'
	from /home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/erb.rb:905:in `result'
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:179:in `block in render'
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:178:in `open'
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:178:in `render'
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:200:in `<main>'
/home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/bosh-release-job47136666/templates/config/config.ini.erb:6:in `parse_ip': uninitialized constant TemplateEvaluationContext::IPAddr (NameError)
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/bosh-release-job47136666/templates/config/config.ini.erb:20:in `get_binding'
	from /home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/erb.rb:905:in `eval'
	from /home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/erb.rb:905:in `result'
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:179:in `block in render'
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:178:in `open'
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:178:in `render'
	from /home/user/.bosh/installations/5dc10bfa-0a81-403e-762a-100f9da080f0/tmp/erb-renderer1376137367/erb-render.rb:200:in `<main>'
':
                exit status 1

Tried with Ruby (apt installed 2.7.0, snap 3.1.0 and rubenv 3.1.0 and 3.0.2) all versions have the same err.
Ping for 127.0.0.1 work well

**Comment by DigitLib** [comment]
This issue is on https://github.com/cloudfoundry/garden-runc-release/issues/216.
