### ISSUE TITLE
A certificate error occurred in the upload-stemcell command(certificate has expired)

### ISSUE THREAD

**Issue by kwonsoonwoo** [cloudfoundry/bosh-deployment#439]
When executing the bosh upload-stemcell command, the following error message appears
```
$ bosh -e stage -n upload-stemcell https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.64

Name               stage
UUID               8918c85c-4e34-4af1-a19f-3ad5498831a5
Version            271.2.0 (00000000)
Director Stemcell  ubuntu-xenial/621.93
CPI                aws_cpi
Features           compiled_package_cache: disabled
                   config_server: enabled
                   local_dns: enabled
                   power_dns: disabled
                   snapshots: enabled
User               admin

Succeeded
Using environment '10.122.100.6' as client 'admin'

Task 238980

Task 238980 | 07:03:22 | Update stemcell: Downloading remote stemcell (00:00:00)
                      L Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
Task 238980 | 07:03:23 | Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)

Task 238980 Started  Thu Aug 25 07:03:22 UTC 2022
Task 238980 Finished Thu Aug 25 07:03:23 UTC 2022
Task 238980 Duration 00:00:01
Task 238980 error

Uploading remote stemcell 'https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.64':
  Expected task '238980' to succeed but state is 'error'

Exit code 1
```

The certificate period still remains, but I don't know why this error occurred.
How to solve it?

```
$ bosh env --details

CERTIFICATE EXPIRY DATE INFORMATION

Certificate                         Expiry Date (UTC)     Days Left
director.ssl.cert                   2032-08-08T06:03:58Z  3635
director.config_server.ca_cert      2032-08-08T06:03:58Z  3635
director.config_server.uaa.ca_cert  2032-08-08T06:03:58Z  3635
nats.tls.ca                         2032-08-08T06:03:58Z  3635
nats.tls.client_ca.certificate      2032-08-08T06:03:58Z  3635
nats.tls.director.certificate       2032-08-08T06:03:58Z  3635
director.db.tls.cert.ca             2024-08-22T17:08:50Z  728

Succeeded
```

**Comment by rkoster** [comment]
Is the issue reproducible in your environment (I was not able to reproduce it in mine)? Also is there any stacktrace you could post in the debug log (bosh task  238980 --debug)?

**Comment by kwonsoonwoo** [comment]
First of all, thank you for leaving a reply.


- **Reproduce the same symptoms**
```
$ bosh -e soonwoo -n upload-stemcell https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.64

Name               soonwoo
UUID               95089975-21ec-4cda-afb8-730c6d102c00
Version            271.2.0 (00000000)
Director Stemcell  ubuntu-xenial/621.93
CPI                aws_cpi
Features           compiled_package_cache: disabled
                   config_server: enabled
                   local_dns: enabled
                   power_dns: disabled
                   snapshots: enabled
User               admin

Succeeded
Using environment '10.90.100.6' as client 'admin'

Task 80

Task 80 | 05:29:59 | Update stemcell: Downloading remote stemcell (00:00:01)
                   L Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
Task 80 | 05:30:00 | Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)

Task 80 Started  Wed Sep 14 05:29:59 UTC 2022
Task 80 Finished Wed Sep 14 05:30:00 UTC 2022
Task 80 Duration 00:00:01
Task 80 error

Uploading remote stemcell 'https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.64':
  Expected task '80' to succeed but state is 'error'

Exit code 1

$ bosh env --details
Using environment '10.90.100.6' as client 'admin'

Name               soonwoo
UUID               95089975-21ec-4cda-afb8-730c6d102c00
Version            271.2.0 (00000000)
Director Stemcell  ubuntu-xenial/621.93
CPI                aws_cpi
Features           compiled_package_cache: disabled
                   config_server: enabled
                   local_dns: enabled
                   power_dns: disabled
                   snapshots: enabled
User               admin

CERTIFICATE EXPIRY DATE INFORMATION

Certificate                         Expiry Date (UTC)     Days Left
director.ssl.cert                   2032-08-23T07:50:25Z  3631
director.config_server.ca_cert      2032-08-23T07:50:25Z  3631
director.config_server.uaa.ca_cert  2032-08-23T07:50:25Z  3631
nats.tls.ca                         2032-08-23T07:50:25Z  3631
nats.tls.client_ca.certificate      2032-08-23T07:50:25Z  3631
nats.tls.director.certificate       2032-08-23T07:50:25Z  3631
director.db.tls.cert.ca             2024-08-22T17:08:50Z  708

Succeeded
```

- **debug log**
```
$ bosh task 80 --debug
Using environment '10.90.100.6' as client 'admin'

Task 80

I, [2022-09-14T05:29:59.396460 #30] [0x3f926c004e78]  INFO -- TaskHelper: Director Version: 271.2.0
I, [2022-09-14T05:29:59.396548 #30] [0x3f926c004e78]  INFO -- TaskHelper: Enqueuing task: 80
I, [2022-09-14T05:29:59.951175 #27116] []  INFO -- DirectorJobRunner: Looking for task with task id 80
D, [2022-09-14T05:29:59.952696 #27116] [] DEBUG -- DirectorJobRunner: (0.000529s) (conn: 47116532896200) SELECT * FROM `tasks` WHERE `id` = 80
I, [2022-09-14T05:29:59.953318 #27116] []  INFO -- DirectorJobRunner: Found task #<Bosh::Director::Models::Task @values={:id=>80, :state=>"processing", :timestamp=>2022-09-14 05:29:59 UTC, :description=>"create stemcell", :result=>nil, :output=>"/var/vcap/store/director/tasks/80", :checkpoint_time=>2022-09-14 05:29:59 UTC, :type=>"update_stemcell", :username=>"admin", :deployment_name=>nil, :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
I, [2022-09-14T05:29:59.953420 #27116] []  INFO -- DirectorJobRunner: Running from worker 'worker_3' on director/2a254ac3-342d-4810-67a5-1800c885c2c7 (127.0.0.1)
I, [2022-09-14T05:29:59.953454 #27116] []  INFO -- DirectorJobRunner: Starting task: 80
I, [2022-09-14T05:29:59.953502 #27116] [task:80]  INFO -- DirectorJobRunner: Creating job
D, [2022-09-14T05:29:59.954457 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.000384s) (conn: 47116532896200) SELECT * FROM `tasks` WHERE `id` = 80
D, [2022-09-14T05:29:59.955321 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.000359s) (conn: 47116532896200) SELECT * FROM `tasks` WHERE `id` = 80
I, [2022-09-14T05:29:59.959818 #27116] [task:80]  INFO -- DirectorJobRunner: Performing task: #<Bosh::Director::Models::Task @values={:id=>80, :state=>"processing", :timestamp=>2022-09-14 05:29:59 UTC, :description=>"create stemcell", :result=>nil, :output=>"/var/vcap/store/director/tasks/80", :checkpoint_time=>2022-09-14 05:29:59 UTC, :type=>"update_stemcell", :username=>"admin", :deployment_name=>nil, :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
D, [2022-09-14T05:29:59.961061 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.000371s) (conn: 47116532896200) BEGIN
D, [2022-09-14T05:29:59.962195 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.000554s) (conn: 47116532896200) UPDATE `tasks` SET `state` = 'processing', `timestamp` = '2022-09-14 05:29:59', `description` = 'create stemcell', `result` = NULL, `output` = '/var/vcap/store/director/tasks/80', `checkpoint_time` = '2022-09-14 05:29:59', `type` = 'update_stemcell', `username` = 'admin', `deployment_name` = NULL, `started_at` = '2022-09-14 05:29:59', `event_output` = '', `result_output` = '', `context_id` = '' WHERE (`id` = 80) LIMIT 1
D, [2022-09-14T05:29:59.966799 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.004500s) (conn: 47116532896200) COMMIT
I, [2022-09-14T05:29:59.966882 #27116] [task:80]  INFO -- DirectorJobRunner: Processing update stemcell
D, [2022-09-14T05:29:59.968997 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.000679s) (conn: 47116532896200) SELECT * FROM `configs` WHERE (`id` IN (SELECT max(`id`) FROM `configs` WHERE (`type` = 'cpi') GROUP BY `name`))
I, [2022-09-14T05:29:59.969141 #27116] [task:80]  INFO -- DirectorJobRunner: Update stemcell
D, [2022-09-14T05:29:59.970235 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.000342s) (conn: 47116532896200) BEGIN
D, [2022-09-14T05:29:59.971032 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.000490s) (conn: 47116532896200) UPDATE `tasks` SET `event_output` = CONCAT(`event_output`, '{\"time\":1663133399,\"stage\":\"Update stemcell\",\"tags\":[],\"total\":6,\"task\":\"Downloading remote stemcell\",\"index\":1,\"state\":\"started\",\"progress\":0}\n') WHERE (`id` = 80)
D, [2022-09-14T05:29:59.975294 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.004174s) (conn: 47116532896200) COMMIT
I, [2022-09-14T05:29:59.975380 #27116] [task:80]  INFO -- DirectorJobRunner: Downloading remote stemcell
I, [2022-09-14T05:29:59.975562 #27116] [task:80]  INFO -- DirectorJobRunner: Downloading remote stemcell from https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.64
D, [2022-09-14T05:30:00.065566 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.000329s) (conn: 47116532896200) BEGIN
D, [2022-09-14T05:30:00.072669 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.006731s) (conn: 47116532896200) UPDATE `tasks` SET `event_output` = CONCAT(`event_output`, '{\"time\":1663133400,\"stage\":\"Update stemcell\",\"tags\":[],\"total\":6,\"task\":\"Downloading remote stemcell\",\"index\":1,\"state\":\"failed\",\"progress\":100,\"data\":{\"error\":\"SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)\"}}\n') WHERE (`id` = 80)
D, [2022-09-14T05:30:00.165220 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.092383s) (conn: 47116532896200) COMMIT
D, [2022-09-14T05:30:00.214827 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.019336s) (conn: 47116532896200) BEGIN
D, [2022-09-14T05:30:00.216129 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.000930s) (conn: 47116532896200) UPDATE `tasks` SET `event_output` = CONCAT(`event_output`, '{\"time\":1663133400,\"error\":{\"code\":100,\"message\":\"SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)\"}}\n') WHERE (`id` = 80)
D, [2022-09-14T05:30:00.242705 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.026433s) (conn: 47116532896200) COMMIT
E, [2022-09-14T05:30:00.242881 #27116] [task:80] ERROR -- DirectorJobRunner: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ea52281b4d5ea6f821ce616a8ca5b181ebf1e4c9/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ea52281b4d5ea6f821ce616a8ca5b181ebf1e4c9/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ea52281b4d5ea6f821ce616a8ca5b181ebf1e4c9/lib/ruby/2.6.0/net/http.rb:996:in `connect'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ea52281b4d5ea6f821ce616a8ca5b181ebf1e4c9/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ea52281b4d5ea6f821ce616a8ca5b181ebf1e4c9/lib/ruby/2.6.0/net/http.rb:919:in `start'
/var/vcap/data/packages/ruby-2.6.5-r0.29.0/ea52281b4d5ea6f821ce616a8ca5b181ebf1e4c9/lib/ruby/2.6.0/net/http.rb:605:in `start'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/download_helper.rb:23:in `download_remote_file'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_stemcell.rb:156:in `download_remote_stemcell'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_stemcell.rb:41:in `block in perform'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:54:in `block in track_and_log'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:52:in `track_and_log'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_stemcell.rb:41:in `perform'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:50:in `with_thread_name'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:9:in `perform'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:32:in `block in perform'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:98:in `block (3 levels) in run'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
/var/vcap/data/packages/director/d0f423a78a6482fec03562879dd6ee04b1807633/gem_home/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2022-09-14T05:30:00.250844 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.007008s) (conn: 47116532896200) SELECT * FROM `tasks` WHERE `id` = 80
D, [2022-09-14T05:30:00.253794 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.000374s) (conn: 47116532896200) BEGIN
D, [2022-09-14T05:30:00.255470 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.001270s) (conn: 47116532896200) UPDATE `tasks` SET `state` = 'error', `timestamp` = '2022-09-14 05:30:00', `description` = 'create stemcell', `result` = 'SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)', `output` = '/var/vcap/store/director/tasks/80', `checkpoint_time` = '2022-09-14 05:29:59', `type` = 'update_stemcell', `username` = 'admin', `deployment_name` = NULL, `started_at` = '2022-09-14 05:29:59', `event_output` = '{\"time\":1663133399,\"stage\":\"Update stemcell\",\"tags\":[],\"total\":6,\"task\":\"Downloading remote stemcell\",\"index\":1,\"state\":\"started\",\"progress\":0}\n{\"time\":1663133400,\"stage\":\"Update stemcell\",\"tags\":[],\"total\":6,\"task\":\"Downloading remote stemcell\",\"index\":1,\"state\":\"failed\",\"progress\":100,\"data\":{\"error\":\"SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)\"}}\n{\"time\":1663133400,\"error\":{\"code\":100,\"message\":\"SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)\"}}\n', `result_output` = '', `context_id` = '' WHERE (`id` = 80) LIMIT 1
D, [2022-09-14T05:30:00.310775 #27116] [task:80] DEBUG -- DirectorJobRunner: (0.055184s) (conn: 47116532896200) COMMIT
I, [2022-09-14T05:30:00.310995 #27116] []  INFO -- DirectorJobRunner: Task took 0.357446045 seconds to process.

Task 80 error

Capturing task '80' output:
  Expected task '80' to succeed but state is 'error'

Exit code 1
```

**Comment by rkoster** [comment]
Could you run `nmap --script=ssl-cert.nse -p 443 bosh.io` from the bosh director? Would be interested in the output.

**Comment by kwonsoonwoo** [comment]
```
bosh/0:~# nmap --script=ssl-cert.nse -p 443 bosh.io

Starting Nmap 7.01 ( https://nmap.org ) at 2022-09-16 00:55 UTC
Nmap scan report for bosh.io (104.21.18.76)
Host is up (0.0016s latency).
Other addresses for bosh.io (not scanned): 172.67.180.240 2606:4700:3037::ac43:b4f0 2606:4700:3030::6815:124c
PORT    STATE SERVICE
443/tcp open  https
| ssl-cert: Subject: commonName=*.bosh.io
| Issuer: commonName=R3/organizationName=Let's Encrypt/countryName=US
| Public Key type: rsa
| Public Key bits: 2048
| Signature Algorithm: sha256WithRSAEncryption
| Not valid before: 2022-08-06T00:08:33
| Not valid after:  2022-11-04T00:08:32
| MD5:   b6be 9c87 d1e7 333e 8fe9 3465 26f3 2782
|_SHA-1: 88cc 9e28 0195 b2d2 e35c 9713 b30e 0413 e4cd f6ff

Nmap done: 1 IP address (1 host up) scanned in 7.27 seconds
```

**Comment by kwonsoonwoo** [comment]
```
bosh/0:~$ chronyc sources -v
210 Number of sources = 5

  .-- Source mode  '^' = server, '=' = peer, '#' = local clock.
 / .- Source state '*' = current synced, '+' = combined , '-' = not combined,
| /   '?' = unreachable, 'x' = time may be in error, '~' = time too variable.
||                                                 .- xxxx [ yyyy ] +/- zzzz
||      Reachability register (octal) -.           |  xxxx = adjusted offset,
||      Log2(Polling interval) --.      |          |  yyyy = measured offset,
||                                \     |          |  zzzz = estimated error.
||                                 |    |           \
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^+ 169.254.169.123               3   9   377    23    +42us[  +42us] +/-  382us
^- time1.google.com              1  10   377   738   -245us[ -242us] +/-   25ms
^* time2.google.com              1  10   377   564    -57us[  -53us] +/- 1388us
^- time3.google.com              1  10   377   712   -183us[ -180us] +/-   26ms
^- time4.google.com              1  10   377   274   +408us[ +408us] +/-   25ms
```

```
$ chronyc tracking
Reference ID    : 216.239.35.4 (time2.google.com)
Stratum         : 2
Ref time (UTC)  : Thu Sep 22 00:51:25 2022
System time     : 0.000030480 seconds slow of NTP time
Last offset     : -0.000012242 seconds
RMS offset      : 0.000053440 seconds
Frequency       : 10.297 ppm slow
Residual freq   : -0.007 ppm
Skew            : 0.015 ppm
Root delay      : 0.001875 seconds
Root dispersion : 0.001118 seconds
Update interval : 1039.2 seconds
Leap status     : Normal
```

```
$ timedatectl
      Local time: Thu 2022-09-22 01:06:55 UTC
  Universal time: Thu 2022-09-22 01:06:55 UTC
        RTC time: Thu 2022-09-22 01:06:56
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

Is there anything wrong with it? Or are there any additional commands I need?

**Comment by rkoster** [comment]
The time / date seems to be okey. Could you run `curl -I -L 'https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.64'`?

**Comment by kwonsoonwoo** [comment]
```
bosh/0:~# curl -I -L 'https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.64'
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
The bosh.io site certificate seems to have expired, what should I do?

**Comment by kwonsoonwoo** [comment]
@beyhan 
Thanks for reply.

- It works fine on local machine(MacOS). like this
```
> curl -I -L 'https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.64'
HTTP/2 302
date: Fri, 23 Sep 2022 02:15:03 GMT
content-type: text/html; charset=utf-8
location: https://s3.amazonaws.com/bosh-aws-light-stemcells/315.64/light-bosh-stemcell-315.64-aws-xen-hvm-ubuntu-xenial-go_agent.tgz
x-vcap-request-id: ce3564f9-0c97-4b61-6861-1d26fa614e72
strict-transport-security: max-age=31536000; includeSubDomains
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=dYZHI2z%2BSFisxV0Ne%2BUR97NBXWwqC4KYj%2BZ2dYPR1KelJYGwqwHUDlGDU%2FOP4Jit43ICHCdOvu0CGWePXNZ%2F9l%2F%2FnycBQW33pbh5wNpD8e008Rf3I3t7wskf"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 74efc52f1dc320c5-NRT
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

HTTP/1.1 200 OK
x-amz-id-2: SNjP1l9qh1wFoX9UGMh+sbNfDZVq/H6WW3b3/8uQZnRyyL/7OQ1a+ca9EUpYgtGzksuuHcfSe58=
x-amz-request-id: JDKV44FGETR0B2VM
Date: Fri, 23 Sep 2022 02:15:05 GMT
Last-Modified: Wed, 03 Jul 2019 00:41:41 GMT
ETag: "c4e901a7ecb5cbac60a3c2f96f995792"
x-amz-version-id: r9Zqx9NWVZzuY8iE8xu301KKrC547GS.
Accept-Ranges: bytes
Content-Type: application/octet-stream
Server: AmazonS3
Content-Length: 19909
```

- It is not used by other IaaS providers, but only in aws.
The bosh director environment is Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-123-generic x86_64).
The environment of the instance with bosh installed is Ubuntu 16.04.5 LTS.

- I think it may be the same reason as this issue.
  - https://github.com/cloudfoundry/bosh/issues/2396

**Comment by rkoster** [comment]
Please update the stemcell for your bosh director 621.93 → 621.280. The stemcell you are currently running is really old and the operation system certificate bundle contained in that is really out of date.

**Comment by kwonsoonwoo** [comment]
Any info on the director stemcell version 621.280?

As a result of searching through google, only the [vmware site](https://network.pivotal.io/products/stemcells-ubuntu-xenial#/releases/1159500) came up.
I signed up but couldn't apply because I couldn't log in.

Instead, I redeployed the bosh director with version 621.125, the most recent version from the existing bosh.io documentation, and the same error occurs.

```
###################
# Upload Stemcell #
###################
/data/cf-ops /data/cf-ops
/data/config/soonwoo /data/cf-ops /data/cf-ops
/data/cf-ops /data/cf-ops
Using environment '10.90.100.6' as client 'admin'

Name               soonwoo
UUID               95089975-21ec-4cda-afb8-730c6d102c00
Version            271.2.0 (00000000)
Director Stemcell  ubuntu-xenial/621.125
CPI                aws_cpi
Features           compiled_package_cache: disabled
                   config_server: enabled
                   local_dns: enabled
                   power_dns: disabled
                   snapshots: enabled
User               admin

Succeeded
Using environment '10.90.100.6' as client 'admin'

Task 99

Task 99 | 06:23:30 | Update stemcell: Downloading remote stemcell (00:00:00)
                   L Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
Task 99 | 06:23:30 | Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)

Task 99 Started  Tue Sep 27 06:23:30 UTC 2022
Task 99 Finished Tue Sep 27 06:23:30 UTC 2022
Task 99 Duration 00:00:00
Task 99 error

Uploading remote stemcell 'https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.64':
  Expected task '99' to succeed but state is 'error'

Exit code 1
```

Should I update the bosh director version?

**Comment by ramonskie** [comment]
it is specifically stemcell related and not with the bosh director.
so you could upgrade only the stemcell of the bosh director

**Comment by kwonsoonwoo** [comment]
@ramonskie 
I found the reason.
Before deploying the cf, I uploaded the stemcell for deploying the cf first, but the xenial version of ami did not exist in AWS.
It seems that a certificate error occurs in the xenial version of stemcell.

I have another problem.
The built-in cf is based on ubuntu-xenial 315.64 version stemcell.
To change this to the bionic version, many things need to be changed, so stability is a problem.

Is there any way to upload ubuntu-xenial version 315.64 to stemcell as a raw image?

**Comment by ramonskie** [comment]
i don't see why changing from xenial to bionic or jammy would cause any statbility issues as cf-deployment is currently tested on both.

its possible to upload full/raw stemcells to a aws deployed director.
but you cannot deploy a director with a full stemcell with bosh create-env

**Comment by kwonsoonwoo** [comment]
@ramonskie 
Like I said above.
When I try to upload stemcell with bosh director, I get "ssl_connect_error" or
I get the message "stemcell does not exist in aws-region".
The reason for this is that aws does not have the xenial stemcell 315.64 version.

The xenial version that can upload-stemcell with bosh director is from version 621.93.

However, since I am using cf-deployment v9.5.0 (see github address below)
(https://github.com/cloudfoundry/cf-deployment/blob/v9.5.0/cf-deployment.yml#L1)
If it is not the xenial version 315.64, I think an error occurs when deploying the releases of cf.

What should I do in this case?

Can I make the 315.64 version of ami?
Or can I ask to recreate the 315.64 version of the ami?

**Comment by ramonskie** [comment]
the xenial-315 line is really old we don't support this anymore and most of those ami's are cleaned up on our part.
as part of a cost reduction program

the only logical route at this point is upgrading the bosh director first and go from there.
upgrading the bosh director should be easy and should not cause any issues

**Comment by rkoster** [comment]
As per https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0010-stemcell-cleanup.md#proposal stemcells older then 3 years can no longer be consumed via a light stemcell.

The heavy stemcell can still be downloaded from here: https://bosh-core-stemcells.s3-accelerate.amazonaws.com/315.64/bosh-stemcell-315.64-aws-xen-hvm-ubuntu-xenial-go_agent.tgz

```
bosh upload-stemcell https://bosh-core-stemcells.s3-accelerate.amazonaws.com/315.64/bosh-stemcell-315.64-aws-xen-hvm-ubuntu-xenial-go_agent.tgz --fix
```

**Comment by kwonsoonwoo** [comment]
@ramonskie @rkoster 
Thank you so much for your sincere answer.

As you said, I'll test it by applying a heavy stemcell.
If I get an error or have any questions, I'll ask again!
