### ISSUE TITLE
bosh create-env error

### ISSUE THREAD

**Issue by ihocho** [cloudfoundry/bosh-deployment#65]
With below "command" i deployed bosh-lite on virtualbox, i got the below "deploy log".

```
--- command ---
bosh create-env bosh.yml --state ./state.json -o virtualbox/cpi.yml -o virtualbox/outbound-network.yml -o bosh-lite.yml -o bosh-lite-runc.yml -o jumpbox-user.yml --vars-store ./creds.yml -v director_name="Bosh Lite Director" -v internal_ip=192.168.150.6 -v internal_gw=192.168.150.1 -v internal_cidr=192.168.150.0/24 -v outbound_network_name=NatNetwork
```

```
--- deploy log ---
Deployment manifest: '/home/ihocho/workspace/bosh-lite/bosh-deployment/bosh.yml'
Deployment state: './state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bosh-virtualbox-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-virtualbox-cpi'... Finished (00:00:01)
  Downloading release 'bosh-warden-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-warden-cpi'... Finished (00:00:00)
  Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'garden-runc'... Skipped [Found in local cache] (00:00:00)
  Validating release 'garden-runc'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:02)
Finished validating (00:00:06)

Started installing CPI
  Compiling package 'golang_1.7/21609f611781e8586e713cfd7ceb389cee429c5a'... Finished (00:00:12)
  Compiling package 'virtualbox_cpi/b088193439d01014a46711523fbcfa00073c6b36'... Finished (00:00:08)
  Installing packages... Finished (00:00:02)
  Rendering job templates... Finished (00:00:00)
  Installing job 'virtualbox_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:23)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3312.15'... Finished (00:00:11)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'sc-71928506-6a9f-4328-533f-f8710fc55469'... Failed (00:00:00)
Failed deploying (00:00:00)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-71928506-6a9f-4328-533f-f8710fc55469':
        Executing external CPI command: '/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/jobs/virtualbox_cpi/bin/cpi':
          Running command: '/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/jobs/virtualbox_cpi/bin/cpi', stdout: '', stderr: '[File System] 2017/04/20 16:14:14 DEBUG - Reading file /home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/jobs/virtualbox_cpi/config/cpi.json
[File System] 2017/04/20 16:14:14 DEBUG - Read content
********************
{"Host":"","Username":"ubuntu","PrivateKey":"","BinPath":"VBoxManage","StoreDir":"~/.bosh_virtualbox_cpi","StorageController":"ide","AutoEnableNetworks":true,"Agent":{"NTP":["time1.google.com","time2.google.com","time3.google.com","time4.google.com"],"blobstore":{"provider":"local","options":{"blobstore_path":"/var/vcap/micro_bosh/data/cache"}},"mbus":"https://mbus:93d1w2uxl04aeezqp107@0.0.0.0:6868"}}

********************
[rpc.JSONDispatcher] 2017/04/20 16:14:14 DEBUG - Request bytes
********************
{"method":"create_vm","arguments":["9f1332c1-1b31-4099-5e70-26af7581bbbb","sc-71928506-6a9f-4328-533f-f8710fc55469",{"cpus":2,"ephemeral_disk":16384,"memory":4096},{"default":{"cloud_properties":{},"default":["dns","gateway"],"dns":["8.8.8.8"],"gateway":"192.168.150.1","ip":"192.168.150.6","netmask":"255.255.255.0","type":"manual"},"outbound":{"cloud_properties":{"name":"NatNetwork","type":"natnetwork"},"type":"dynamic"}},[],{"bosh":{"password":"*"}}],"context":{"director_uuid":"99c0a426-9b2a-4acd-6b9c-5cdefd476972"}}
********************
[rpc.JSONDispatcher] 2017/04/20 16:14:14 DEBUG - Deserialized request
********************
{create_vm [9f1332c1-1b31-4099-5e70-26af7581bbbb sc-71928506-6a9f-4328-533f-f8710fc55469 map[cpus:%!!(MISSING)s(float64=2) ephemeral_disk:%!!(MISSING)s(float64=16384) memory:%!!(MISSING)s(float64=4096)] map[default:map[type:manual cloud_properties:map[] default:[dns gateway] dns:[8.8.8.8] gateway:192.168.150.1 ip:192.168.150.6 netmask:255.255.255.0] outbound:map[cloud_properties:map[type:natnetwork name:NatNetwork] type:dynamic]] [] map[bosh:map[password:*]]] {{"director_uuid":"99c0a426-9b2a-4acd-6b9c-5cdefd476972"}}}
********************
[driver.LocalRunner] 2017/04/20 16:14:14 DEBUG - Execute 'VBoxManage list' 'natnetworks'
[Cmd Runner] 2017/04/20 16:14:14 DEBUG - Running command 'VBoxManage list natnetworks'
[Cmd Runner] 2017/04/20 16:14:14 DEBUG - Stdout: NetworkName:    NatNetwork
IP:             10.0.2.1
Network:        10.0.2.0/24
IPv6 Enabled:   No
IPv6 Prefix:    fd17:625c:f037:2::/64
DHCP Enabled:   Yes
Enabled:        Yes
Port-forwarding (ipv4)
        ssh1:tcp:[127.0.0.1]:1234:[10.0.2.15]:22
        ssh2:tcp:[127.0.0.1]:2345:[10.0.2.4]:22
loopback mappings (ipv4)
        127.0.0.1=2

[Cmd Runner] 2017/04/20 16:14:14 DEBUG - Stderr: 
[Cmd Runner] 2017/04/20 16:14:14 DEBUG - Successful: true (0)
panic: Internal inconsistency: Expected len(^([a-zA-Z0-9\s]+):\s*(.+)?$ matches) == 3: line 'Port-forwarding (ipv4)'

goroutine 1 [running]:
panic(0x670120, 0xc4200fc0f0)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/packages/golang_1.7/src/runtime/panic.go:500 +0x1a1
github.com/cppforlife/bosh-virtualbox-cpi/vm/network.Networks.NATNetworks(0x809740, 0xc42000edc0, 0x80b6c0, 0xc42000d6e0, 0x3, 0xc4200d8136, 0x0, 0x4, 0xc420063da8)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-virtualbox-cpi/vm/network/networks.go:62 +0x89c
github.com/cppforlife/bosh-virtualbox-cpi/vm.natNetworksAdapter.List(0x809740, 0xc42000edc0, 0x80b6c0, 0xc42000d6e0, 0xc41fff8ffc, 0x0, 0x1, 0xc41fff8ffd, 0xc4200cdc40)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-virtualbox-cpi/vm/host.go:163 +0x4d
github.com/cppforlife/bosh-virtualbox-cpi/vm.(*natNetworksAdapter).List(0xc4200e0040, 0x20, 0x6bbb80, 0xc4200d657b, 0x2, 0x20)
	<autogenerated>:65 +0x6d
github.com/cppforlife/bosh-virtualbox-cpi/vm.(*hostNetwork).Enable(0xc4200cdec0, 0xc4200cdd38, 0xc4200e0040)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-virtualbox-cpi/vm/host.go:84 +0x56
github.com/cppforlife/bosh-virtualbox-cpi/vm.Host.EnableNetworks(0x809740, 0xc42000edc0, 0x80b6c0, 0xc42000d6e0, 0xc4200d83f0, 0x0, 0x6ccea5)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-virtualbox-cpi/vm/host.go:37 +0x2af
github.com/cppforlife/bosh-virtualbox-cpi/vm.Factory.Create(0xc42004fa80, 0x1a, 0xc420015910, 0x3, 0x1, 0x8077c0, 0x846810, 0x809740, 0xc42000edc0, 0x809e00, ...)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-virtualbox-cpi/vm/factory.go:83 +0x1011
github.com/cppforlife/bosh-virtualbox-cpi/vm.(*Factory).Create(0xc42007f8c0, 0xc42000de90, 0x24, 0x809f00, 0xc42000f090, 0x807940, 0xc42004ff20, 0xc4200d8150, 0xc4200d8240, 0x6eec1c, ...)
	<autogenerated>:1 +0x10c
github.com/cppforlife/bosh-virtualbox-cpi/cpi.VMs.CreateVM(0x807b00, 0xc42008bf40, 0x807b80, 0xc42007f8c0, 0x807bc0, 0xc42007f9e0, 0xc42000de90, 0x24, 0xc42000dec0, 0x27, ...)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-virtualbox-cpi/cpi/vms.go:31 +0x208
github.com/cppforlife/bosh-virtualbox-cpi/cpi.(*CPI).CreateVM(0xc420084d00, 0xc42000de90, 0x24, 0xc42000dec0, 0x27, 0x807940, 0xc42004ff20, 0xc4200d8150, 0x846810, 0x0, ...)
	<autogenerated>:23 +0x103
github.com/cppforlife/bosh-cpi-go/apiv1.ActionFactory.Create.func3(0xc42000de90, 0x24, 0xc42000dec0, 0x27, 0xc42000df20, 0x2f, 0x30, 0xc4200d8150, 0x846810, 0x0, ...)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-cpi-go/apiv1/action_factory.go:44 +0x140
reflect.Value.call(0x68f480, 0xc42004faa0, 0x13, 0x6cc25c, 0x4, 0xc4200c40c0, 0x6, 0x8, 0xc420015f40, 0x681000, ...)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/packages/golang_1.7/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x68f480, 0xc42004faa0, 0x13, 0xc4200c40c0, 0x6, 0x8, 0x6, 0x8, 0x0)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/packages/golang_1.7/src/reflect/value.go:302 +0xa4
github.com/cppforlife/bosh-cpi-go/rpc.JSONCaller.Call(0x68f480, 0xc42004faa0, 0xc4200108a0, 0x6, 0x6, 0x68f480, 0xc42004faa0, 0x0, 0x0)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-cpi-go/rpc/json_caller.go:44 +0x313
github.com/cppforlife/bosh-cpi-go/rpc.(*JSONCaller).Call(0x846810, 0x68f480, 0xc42004faa0, 0xc4200108a0, 0x6, 0x6, 0xc42004faa0, 0x0, 0x0, 0xc42002a008)
	<autogenerated>:5 +0x81
github.com/cppforlife/bosh-cpi-go/rpc.JSONDispatcher.Dispatch(0x807800, 0xc420015a20, 0x807980, 0x846810, 0x6d04ef, 0x12, 0x80b6c0, 0xc42000d6e0, 0xc4200d2600, 0x20b, ...)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-cpi-go/rpc/json_dispatcher.go:72 +0x483
github.com/cppforlife/bosh-cpi-go/rpc.(*JSONDispatcher).Dispatch(0xc420012fc0, 0xc4200d2600, 0x20b, 0x600, 0x600, 0x0, 0x0)
	<autogenerated>:12 +0x93
github.com/cppforlife/bosh-cpi-go/rpc.CLI.ServeOnce(0x807000, 0xc42002a008, 0x807040, 0xc42002a010, 0x8079c0, 0xc420012fc0, 0x6cc058, 0x3, 0x80b6c0, 0xc42000d6e0, ...)
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-cpi-go/rpc/cli.go:38 +0x272
main.main()
	/home/ihocho/.bosh/installations/a97ca73f-2e3f-4cb8-6be2-81fb01ca6a19/tmp/bosh-release-pkg684871484/src/github.com/cppforlife/bosh-virtualbox-cpi/main/main.go:43 +0xabe
':
            exit status 2

Exit code 1

```

**Comment by dpb587-pivotal** [comment]
It seems you have some existing VMs which are running in VirtualBox in a way that the CPI does not support. I don't think the VirtualBox NAT Network should be used to forward ports anyways since they are accessible directly via IP.

I recommend you edit the Settings of your running VMs by visiting the Network tab and removing Port Forwarding for NAT Network interfaces - you may see an "Invalid settings detected" notification at the bottom of the dialog. If you're using Vagrant or manual VBoxManage commands, you may need to edit those commands directly.

**Comment by cppforlife** [comment]
@ihocho should be fixed by https://github.com/cloudfoundry/bosh-deployment/commit/506260980fb43f60da3e405f5377b7d593950236
